### ISSUE TITLE
ObjectDisposedException thrown when switching or removing library while asset is selected 

### ISSUE THREAD

**Issue by DjPale** [CookieBadger/assetplacer-docs#2] opened 2023-05-31 19:06 UTC
After grouping and saving a set of asset libraries (imported from Kenney Nature Pack), the plugin crashes after trying to switch between different libraries and it is not possible to select different objects anymore.

Using Mono version of Godot 4.0.3 with Windows .NET SDK 6.0 and plugin version 1.0.1

```
  modules/mono/glue/runtime_interop.cpp:1303 - System.ObjectDisposedException: Cannot access a disposed object.
  Object name: 'AssetPlacer.AssetPlacerButton'.
     at Godot.GodotObject.GetPtr(GodotObject instance) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/GodotObject.base.cs:line 73
     at Godot.Control.SetTheme(Theme theme) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Generated/GodotObjects/Control.cs:line 1714
     at Godot.Control.set_Theme(Theme value) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Generated/GodotObjects/Control.cs:line 971
     at AssetPlacer.AssetPlacerUi.DeselectButton() in D:\src\Games\Godot\Diorama Disc Golf\game\addons\assetplacer\ui\AssetPlacerUi.cs:line 550
     at AssetPlacer.AssetPlacerUi.AssetButtonPressed(AssetPlacerButton button, String assetPath, String assetName) in D:\src\Games\Godot\Diorama Disc Golf\game\addons\assetplacer\ui\AssetPlacerUi.cs:line 515
     at AssetPlacer.AssetPlacerButton.RaiseGodotClassSignalCallbacks(godot_string_name& signal, NativeVariantPtrArgs args) in D:\src\Games\Godot\Diorama Disc Golf\game\Godot.SourceGenerators\Godot.SourceGenerators.ScriptSignalsGenerator\AssetPlacer.AssetPlacerButton_ScriptSignals.generated.cs:line 40
     at Godot.Bridge.ScriptManagerBridge.RaiseEventSignal(IntPtr ownerGCHandlePtr, godot_string_name* eventSignalName, godot_variant** args, Int32 argCount, godot_bool* outOwnerIsNull) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.cs:line 368
```

**Comment by CookieBadger** [comment] 2023-06-01 13:50
Thank you very much, I will look into it. For now, disabling and re-enabling the plugin, or in the worst case, restarting the Godot editor will make the plugin work again.

As far as I know, those types of errors usually occur when you rebuild the code while the plugin is running, after making some changes (changes don't have to be inside plugin).

**Comment by DjPale** [comment] 2023-06-02 06:31
Restarting Godot helps, but it happens almost immediately again - seems to be connected with switching between asset library-tabs somehow. I can see if I can reproduce it consistently later today.

**Comment by CookieBadger** [comment] 2023-06-06 16:14
I know what the issue is. You can avoid the issue by making sure you deselect the current asset before you switch or remove a library. Will be fixed in a future version.

**Comment by CookieBadger** [comment] 2023-07-08 05:42
Fixed in new version. Let me know if you still encounter the issue.

**Closed by CookieBadger** 2023-07-08 05:42 UTC
